version: '3.1'
services:
  ovehub-ove-ove:
    image: ovehub/ove:0.5.0
    restart: unless-stopped
    volumes:
      - ./config/Spaces.json:/usr/src/app/packages/ove-core/dist/client/Spaces.json:ro

  ovehub-ove-apps:
    image: ovehub/ove-apps:0.5.0
    restart: unless-stopped
    depends_on:
      - ovehub-ove-ove
    environment:
      OVE_HOST: "0.0.0.0:8080"
      OPENVIDU_HOST: "https://0.0.0.0:443"
      OPENVIDU_SECRET: "MY_SECRET"

  ovehub-ove-ui:
    image: ovehub/ove-ui:0.2.0
    restart: unless-stopped
    depends_on:
      - ovehub-ove-ove
      - ovehub-ove-apps
    environment:
      OVE_HOST: "0.0.0.0:8080"

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - ovehub-ove-ove
      - ovehub-ove-apps
      - ovehub-ove-ui
    ports:
      - "8080:8080"
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
