services:
  dash:
    build: .
    depends_on:
    - nginx
    environment:
      API_URL: http://192.168.1.252:8080
      DH_URL: http://127.0.0.1
      PLOT_URL: http://192.168.1.252:8050
    ports:
    - 8050:8050
    volumes:
    - ./app:/app
    - ./logs:/logs
  nginx:
    depends_on:
    - ovehub-ove-ove
    - ovehub-ove-apps
    - ovehub-ove-ui
    image: nginx:alpine
    ports:
    - 8080:8080
    restart: unless-stopped
    volumes:
    - ./config/default.conf:/etc/nginx/conf.d/default.conf:ro
    - ./logs/nginx.log:/etc/nginx/logs/error.log
  ovehub-ove-apps:
    depends_on:
    - ovehub-ove-ove
    environment:
      OPENVIDU_HOST: https://146.179.34.13:4443
      OPENVIDU_SECRET: MY_SECRET
      OVE_HOST: 192.168.1.252:8080
    image: ovehub/ove-apps:0.6.4
    restart: unless-stopped
  ovehub-ove-ove:
    image: ovehub/ove:0.6.3
    restart: unless-stopped
    volumes:
    - ./config/Spaces.json:/usr/src/app/packages/ove-core/dist/client/Spaces.json:ro
  ovehub-ove-ui:
    depends_on:
    - ovehub-ove-ove
    - ovehub-ove-apps
    environment:
      OVE_HOST: 192.168.1.252:8080
    image: ovehub/ove-ui:0.2.1
    restart: unless-stopped
version: '3.1'
